exec-once = steam -silent
exec-once = vesktop
exec-once = spotify-launcher

# Default workspaces
windowrule = match:class vesktop, workspace 6 silent
windowrule = match:class Spotify, workspace 7 silent
