source = colors.conf

general {
    ignore_empty_input = true
}

background {
    path = $image
    blur_passes = 3
}

label {
    monitor = $MAIN_MONITOR

    text = cmd[update:1000] echo "<b>$(date '+%A, %b %d')</b>"
    color = $on_surface
    font_size = 24
    font_family = NotoSans Nerd Font Propo

    position = 0, -140
    valign = top
}

label {
    monitor = $MAIN_MONITOR

    text = <b>$TIME</b>
    color = $on_surface
    font_size = 112
    font_family = NotoSans Nerd Font Propo

    position = 0, -180
    valign = top
}

image {
    monitor = $MAIN_MONITOR

    path = ~/.dotfiles/assets/avatar.png
    size = 96
    rounding = -1
    border_size = 0

    position = 0, 230
    valign = bottom
}

label {
    monitor = $MAIN_MONITOR

    text = cmd[] echo "<b>${USER^}</b>"
    color = $on_surface
    font_size = 14
    font_family = NotoSans Nerd Font Propo

    position = 0, 180
    valign = bottom
}

input-field {
    monitor = $MAIN_MONITOR

    size = 280, 40
    outline_thickness = 1
    dots_spacing = 0.35
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = $on_surface
    fade_on_empty = false
    placeholder_text = <span foreground="white">Enter Password</span>
    check_color = rgba(0, 0, 0, 0)
    fail_color = rgba(0, 0, 0, 0)
    fail_text = <span foreground="white">Incorrect password</span>

    position = 0, 110
    valign = bottom
}

label {
    monitor = $MAIN_MONITOR

    text = cmd[update:10] \
        [ "$(cat /sys/class/leds/input*::capslock/brightness | \
        head -n 1)" -eq 1 ] && echo "<b>  Caps Lock On</b>"
    color = $on_surface
    font_size = 10
    font_family = NotoSans Nerd Font Propo

    position = 0, 70
    valign = bottom
}

animations {
    animation = inputFieldDots, 0, 0, default
}
