#!/bin/bash

MONITOR="${MAIN_MONITOR:-}"

PLAYER="$(playerctl -l | head -n1)"

[ -z "$PLAYER" ] && exit 0

case "$1" in
  play-pause|next|previous)
    swayosd-client \
      --monitor "$MONITOR" \
      --player "$PLAYER" \
      --playerctl "$1"
    ;;
  volume)
    playerctl --player="$PLAYER" volume "$2" && \
    swayosd-client \
      --monitor "$MONITOR" \
      --custom-icon "audio-x-generic-symbolic" \
      --custom-progress "$(playerctl --player="$PLAYER" volume)"
    ;;
esac
