#!/bin/bash
set -e

ACCENT="$1"

PAPIRUS="/usr/share/icons/Papirus"
SIZES="22x22 24x24 32x32 48x48 64x64 96x96 128x128"

MID="$(pastel mix $ACCENT black --fraction 0.8 | pastel format hex)"
DARK="$(pastel mix $ACCENT black --fraction 0.35 | pastel format hex)"

for size in $SIZES; do
    SRC="$PAPIRUS/$size/places"

    for f in "$SRC"/folder-blue{,-*}.svg "$SRC"/user-blue-*.svg; do
        (
            new="${f##*/}"
            new="${new/blue/matugen}"
            sed -e "s/#5294e2/$ACCENT/g" \
                -e "s/#4877b1/$MID/g" \
                -e "s/#1d344f/$DARK/g" \
                "$f" > "$SRC/$new"
        ) &
    done
done
wait
