#!/bin/bash

LOGO_DIR="$HOME/.config/fastfetch/logos"

choices=(
    "nerv"
    "copland"
    "yorha"
    "arasaka"
    "teto"
)

get_quote() {
    case "$1" in
        nerv)
            echo "GOD'S IN HIS HEAVEN. ALL'S RIGHT WITH THE WORLD."
            ;;
        copland)
            echo "Let's all love Lain!"
            ;;
        yorha)
            echo "For the Glory of Mankind"
            ;;
        arasaka)
            echo "A Bright Future, Together."
            ;;
        teto)
            echo "恋をして　ふられ　また　捨てられて"
            ;;
    esac
}

if [[ " ${choices[*]} " =~ " $1 " ]]; then
    choice="$1"
    shift
else
    choice=$(printf "%s\n" "${choices[@]}" | shuf -n1)
fi

quote=$(get_quote "$choice")

FASTFETCH_QUOTE="$quote" fastfetch --logo "$LOGO_DIR/$choice.txt" "$@"
