#!/bin/bash

MODE="$1"

# Don't start another instance if slurp is already running
pgrep -x slurp && exit 0

DIR="$HOME/Pictures/Screenshots"
THUMB_DIR="/tmp/screenshots"
mkdir -p "$DIR"
mkdir -p "$THUMB_DIR"

TIMESTAMP="$(date +%Y-%m-%d-%H%M%S)"
FILE="$DIR/${TIMESTAMP}.png"
THUMB="${THUMB_DIR}/thumb_${TIMESTAMP}.png"

# Mooch off Quickshell's colors
BG=$(
    jq -r '.md3.background' \
    ~/.local/state/quickshell/generated/colors.json
)
BG=${BG:-"#000000"} # Default to black

FG=$(
    jq -r '.md3.on_background' \
    ~/.local/state/quickshell/generated/colors.json
)
FG=${FG:-"#ffffff"} # Default to white

SLURP=(
    slurp
    -b "${BG}80"
    -B "${BG}80"
    -c "${FG}80"
    -F 'NotoSans Nerd Font Propo'
)

# Capture region
case "$MODE" in
    output)
        MONITOR_COUNT=$(hyprctl -j monitors | jq length)

        if [ "$MONITOR_COUNT" -eq 1 ]; then
            # Single monitor: skip slurp and use full monitor
            REGION=$(
                hyprctl -j monitors |
                jq -r '.[0] | "\(.x),\(.y) \(.width)x\(.height)"'
            )
        else
            # -o: output, -r: disable region select, -w: border width
            REGION=$("${SLURP[@]}" -o -r -w 0)
        fi
        ;;
    window)
        # Get active workspaces
        WORKSPACES=$(
            hyprctl -j monitors |
            jq -c '[.[].activeWorkspace.id]'
        )

        # Draw regions for each visible window
        # -r: disable region select
        REGION=$(
            hyprctl -j clients |
            jq -r --argjson ws "$WORKSPACES" '
                .[]
                | select(
                    .mapped
                    and (.hidden | not)
                    and (.workspace.id as $id | $ws | index($id))
                )
                | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"
            ' |
            "${SLURP[@]}" -r
        )
        ;;
    *)
        # -d: show dimensions
        REGION=$("${SLURP[@]}" -d)
        ;;
esac

[ -z "$REGION" ] && exit 0

# Take screenshot
grim -g "$REGION" "$FILE" || exit 1

# Copy to clipboard
wl-copy < "$FILE"

# Generate thumbnail
magick "$FILE" -thumbnail 250x250 "$THUMB"

# Notify user
ACTION=$(notify-send \
    -a "Arch Linux" \
    --action="default=Open" \
    -i "$THUMB" \
    "Screenshot saved" \
    "Image saved to $FILE"
)

# Open directory if notification clicked
if [[ "$ACTION" == "default" ]]; then
    xdg-open "$(dirname "$FILE")" &>/dev/null &
fi
