#!/bin/bash

# Get the number of available updates
UPDATES=$(checkupdates | wc -l)

# If there are updates, send a notification
if [[ "$UPDATES" -gt 0 ]]; then
    ACTION=$(notify-send -a "Arch Linux" \
        --action="default=Update" \
        "Software Updates Available" \
        "$UPDATES updates available")

    if [[ "$ACTION" == "default" ]]; then
        ghostty -e bash -c "yay -Syu && \
            echo 'Update complete!' || \
            echo 'Update failed.'; \
            read -p 'Press Enter to close...'"
    fi
fi
